name: Build and package TYPE_MONEY plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin.yml@v1
    with:
      plugin_name: type-money
      plugin_directory: type_money
      build_target: type_money
      plugin_library: type_money.so
      cmake_options: -DPLUGIN_DATE_EXTRA=DYNAMIC
      test_suite: type_money
      run_tests: false
